typeOrm:
  port: CEMEVYF_HEALTH_ORDERS_SERVICE_DB_PORT
  database: CEMEVYF_HEALTH_ORDERS_SERVICE_DB_NAME
  host: CEMEVYF_HEALTH_ORDERS_SERVICE_DB_HOST
  username: CEMEVYF_HEALTH_ORDERS_SERVICE_DB_USERNAME
  password: CEMEVYF_HEALTH_ORDERS_SERVICE_DB_PASSWORD
port: CEMEVYF_HEALTH_ORDERS_SERVICE_SERVER_PORT
logLevel: CEMEVYF_HEALTH_ORDERS_SERVICE_LOG_LEVEL
crypto:
  encryptionKey: CEMEVYF_HEALTH_ORDERS_SERVICE_ENCRYPTION_KEY
  iv: CEMEVYF_HEALTH_ORDERS_SERVICE_ENCRYPTION_IV
files:
  maxFileSizeInMb: CEMEVYF_HEALTH_ORDERS_SERVICE_FILE_MAX_FILE_SIZE_IN_MB
serviceConfig:
  messageServiceUrl: CEMEVYF_HEALTH_ORDERS_SERVICE_MESSAGE_SERVICE_URL
swagger:
  feature: CEMEVYF_HEALTH_ORDERS_SERVICE_SWAGGER_FEATURE
