typeOrm:
  port: CEMEVYF_QUOTATION_SERVICE_DB_PORT
  database: CEMEVYF_QUOTATION_SERVICE_DB_NAME
  host: CEMEVYF_QUOTATION_SERVICE_DB_HOST
  username: CEMEVYF_QUOTATION_SERVICE_DB_USERNAME
  password: CEMEVYF_QUOTATION_SERVICE_DB_PASSWORD
port: CEMEVYF_QUOTATION_SERVICE_SERVER_PORT
logLevel: CEMEVYF_QUOTATION_SERVICE_LOG_LEVEL
crypto:
  encryptionKey: CEMEVYF_QUOTATION_SERVICE_ENCRYPTION_KEY
  iv: CEMEVYF_QUOTATION_SERVICE_ENCRYPTION_IV
files:
  maxFileSizeInMb: CEMEVYF_QUOTATION_SERVICE_FILE_MAX_FILE_SIZE_IN_MB
serviceConfig:
  messageServiceUrl: CEMEVYF_QUOTATION_SERVICE_MESSAGE_SERVICE_URL
