typeOrm:
  type: mysql
  host: localhost
  port: 3306
  database: health_orders
  syncronize: false
  logging: [ "error" ]
  multipleStatements: true
  timezone: Z
  cli:
    migrationsDir: migrations
port: 9900
logLevel: warn
crypto:
  encryptionKey: 'CEMEVYF encryption key'
  iv: 'CEK iv'
serviceConfig:
  messageServiceUrl: http://localhost:3000
files:
  maxFileSizeInMb: 5
